---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  listen: aptcacheupdate

- name: Enable or restart Soft Serve service
  ansible.builtin.systemd:
    name: soft-serve.service
    state: restarted
    daemon_reload: true
    enabled: true
    masked: false
    scope: user
  listen: enablerestartsoftserve
