---
- name: Start Samba service
  become: true
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true
    masked: false
  listen: startsamba

- name: Restart Samba service
  become: true
  ansible.builtin.service:
    name: smbd
    state: restarted
  listen: restartsamba