---
# samba: Role for Samba
- name: Install Samba
  become: true
  ansible.builtin.apt:
    name: ['samba', 'samba-common']
    state: present
  notify: startsamba

- name: Install Samba config
  become: true
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: restartsamba

- name: Wait for Samba services to (re)start
  ansible.builtin.meta: flush_handlers
