---
# mergerfs pool configuration
- name: Create /mnt points for pools
  become: true
  file:
    dest: "{{ item.mnt }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items:
    - "{{ fspools }}"

- name: Mount pools
  become: true
  mount:
    path: "{{ item.mnt }}"
    src: "{{ item.src }}"
    opts: "use_ino,{{ mergerfscache }},dropcacheonclose=true,category.create=mfs,allow_other,minfreespace=50G,fsname=mergerfs"
    fstype: fuse.mergerfs
    state: mounted
  with_items: "{{ fspools }}"