---
# mergerfs: Role for mergerfs
- name: Import filesystem utils installation tasks
  ansible.builtin.import_tasks:
    file: install.yml

- name: Get package info
  ansible.builtin.package_facts:
    manager: apt

- name: Set caching option
  ansible.builtin.set_fact:
    mergerfscache: "{{ 'cache.files=off' if ansible_facts.packages['mergerfs'][0].version is version('2.28', '>=') else 'direct_io' }}"

- name: Import pool configuration tasks
  ansible.builtin.import_tasks:
    file: config.yml
