---
# mergerfs: Role for mergerfs
- name: Import installation tasks
  ansible.builtin.import_tasks:
    file: install.yml

- name: Import pool configuration tasks
  ansible.builtin.import_tasks:
    file: config.yml