---
# SSH configuration
- name: config | Create SSH key for server
  become: true
  ansible.builtin.user:
    name: root
    generate_ssh_key: true
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
