---
# rsnapshot installation
- name: install | Install rsnapshot
  become: true
  ansible.builtin.apt:
    name: rsnapshot
    state: present

- name: install | Install rsnapshot config
  become: true
  ansible.builtin.template:
    src: rsnapshot.conf.j2
    dest: /etc/rsnapshot.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: install | Creates a cronjob in /etc/cron.d to run rsnapshot
  become: true
  ansible.builtin.cron:
    name: "{{ item.name }}"
    user: root
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    job: "{{ item.job }}"
    cron_file: rsnapshot
  with_items: "{{ bmajor_rsnapshot_crontab }}"
  when: online
