---
# bmajor: Role for backup server
- name: Import rsnapshot installation tasks
  ansible.builtin.import_tasks:
    file: rsnapshot.yml

- name: Import SSH configuration tasks
  ansible.builtin.import_tasks:
    file: config.yml