---
# mpd: Role for MPD
- name: Install MPD
  become: true
  ansible.builtin.apt:
    name: mpd
    state: present

- name: Configure MPD
  ansible.builtin.template:
    src: mpd.conf.j2
    dest: "{{ mpd_config }}/mpd.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    backup: true
  notify: enablerestartmpd

- name: Wait for MPD service to restart
  ansible.builtin.meta: flush_handlers
