---
- name: Backup server configuration
  hosts: backup

  pre_tasks:
    - name: Update apt cache
      become: true
      apt:
        cache_valid_time: 3600
        upgrade: "yes"

  roles:
    - bmajor