---
- name: Media server configuration
  hosts: media

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        cache_valid_time: 3600
        upgrade: "yes"

  roles:
    - mpd