---
- name: NAS configuration
  hosts: nas

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        cache_valid_time: 3600
        upgrade: "yes"

  roles:
    - diskconf
    - mergerfs
    - bminor
    - softserve
    - samba
