---
# handlers for mpd
- name: Enable or reload mpd service
  ansible.builtin.systemd:
    name: mpd.service
    enabled: true
    masked: false
    scope: user
    state: restarted
  listen: enablereloadmpd