---
# SSH configuration for backup pulling
- name: Install the `rsync-wrapper.sh` script, called by bmajor
  become: true
  ansible.builtin.copy:
    src: rsync-wrapper.sh
    dest: /usr/local/bin/rsync-wrapper.sh
    owner: root
    group: root
    mode: 0774

- name: Retrieve the SSH public key on bmajor
  delegate_to: bmajor_host
  remote_user: root
  ansible.builtin.command:
    cmd: "cat $HOME/.ssh/{{ rsnapshot_master_ssh_key }}.pub"
  register: bmajor_ssh_pubkey
  changed_when: false

- name: Set the SSH public key for the backup system user
  become: true
  ansible.posix.authorized_key:
    user: bminor
    state: present
    key: "{{ bmajor_ssh_pubkey.stdout }}"
    key_options: "no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding"
