---
# Disks configuration
- name: Partition disks
  become: true
  community.general.parted:
    device: "/dev/disk/by-id/ata-{{ item.name }}"
    number: 1
    label: gpt
    fstype: "{{ item.fs }}"
    state: present
  when: item.new
  with_items: "{{ disks }}"

- name: Format disks
  become: true
  community.general.filesystem:
    dev: "/dev/disk/by-id/ata-{{ item.name }}-part1"
    fstype: "{{ item.fs }}"
  when: item.new
  with_items: "{{ disks }}"
  notify: diskburnintest

- name: Create /mnt points for disks
  become: true
  ansible.builtin.file:
    dest: "{{ item.mnt }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items:
    - "{{ disks }}"

- name: Mount disks
  become: true
  ansible.posix.mount:
    path: "{{ item.mnt }}"
    src: "/dev/disk/by-id/ata-{{ item.name }}-part1"
    fstype: "{{ item.fs }}"
    state: mounted
  with_items: "{{ disks }}"