---
# disks configuration
- name: Partition disks
  become: true
  parted:
    device: "/dev/disk/by-id/ata-{{ item.name }}"
    number: 1
    label: gpt
    # fstype: "{{ item.fs }}" # only in >= v2.10
    state: present
  when: item.new
  with_items: "{{ disks }}"

- name: Format disks
  become: true
  filesystem:
    dev: "/dev/disk/by-id/ata-{{ item.name }}-part1"
    fstype: "{{ item.fs }}"
  when: item.new
  with_items: "{{ disks }}"
  notify: diskburnintest

- name: Create /mnt points for disks
  become: true
  file:
    dest: "{{ item.mnt }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items:
    - "{{ disks }}"

- name: Mount disks
  become: true
  mount:
    path: "{{ item.mnt }}"
    src: "/dev/disk/by-id/ata-{{ item.name }}-part1"
    fstype: "{{ item.fs }}"
    state: mounted
  with_items: "{{ disks }}"