---
# Disk-burnin script installation
- name: Install e2fsprogs and smartmontools
  become: true
  ansible.builtin.apt:
    name: ['e2fsprogs', 'smartmontools']
    state: present

- name: Ensure directory for scripts exists
  ansible.builtin.file:
    path: ~/.scripts
    state: directory
    mode: 0775

- name: Ensure directory for tar extraction exists
  ansible.builtin.file:
    path: /tmp/disk-burnin
    state: directory
    mode: 0700

- name: Get latest release of disk burn-in script
  ansible.builtin.uri:
    url: https://api.github.com/repos/Spearfoot/disk-burnin-and-testing/releases/latest
    return_content: true
  check_mode: false
  register: json_reponse

- name: Download latest release of disk burn-in script
  ansible.builtin.get_url:
    url: "{{ json_reponse.json.tarball_url }}"
    dest: /tmp/disk-burnin/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  notify: extractdiskburnin
  register: tar

- name: Wait for disk burn-in script installation to complete
  ansible.builtin.meta: flush_handlers

- name: Install SMART-reporting script
  ansible.builtin.template:
    src: smart.sh.j2
    dest: ~/.scripts/smart.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0774

- name: Creates a cronjob in /etc/cron.d to report SMART status
  become: true
  ansible.builtin.cron:
    name: weekly SMART reporting
    user: root
    weekday: "1"
    hour: "8"
    minute: "0"
    job: "/home/{{ ansible_user }}/.scripts/smart.sh"
    cron_file: smart
