---
# installation of prerequistes and scripts
- name: Install e2fsprogs and smartmontools
  become: true
  apt:
    name: ['e2fsprogs', 'smartmontools']
    state: present

- name: Ensure directory for scripts exists
  file: 
    dest: ~/.scripts/
    state: directory

# TODO: Get script direct from github
- name: Install disk burn-in script
  copy: 
    src: disk-burnin.sh
    dest: ~/.scripts/disk-burnin.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Install SMART-reporting script
  template:
    src: smart.sh.j2
    dest: ~/.scripts/smart.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Creates a cronjob in /etc/cron.d to report SMART status
  become: true
  cron:
    name: weekly SMART reporting
    user: root
    weekday: "1"
    hour: "8"
    minute: "0"
    job: "/home/{{ ansible_user }}/.scripts/smart.sh"
    cron_file: smart